version: '3.8'

services:
  web:
    container_name: api.osb.im
    image: api.osb.im:1.${BUILD_NUMBER}
    restart: always
    ports:
      - 9060:80
    networks:
      - npm

networks:
  npm:
    external:
      name: npm